apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
data:
  mongod.conf: |
    storage:
      dbPath: /data/db
    systemLog:
      destination: file
      path: /data/db/mongodb.log
      logAppend: true
    net:
      port: 27017
      bindIpAll: true
